# Generated by Django 4.0.2 on 2022-02-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('genre', models.CharField(max_length=32, verbose_name='Жанр')),
                ('age', models.IntegerField(verbose_name='Возрастное ограничение')),
            ],
        ),
    ]
