# Generated by Django 4.0.2 on 2022-02-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_items_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='age',
            field=models.IntegerField(choices=[(6, '6'), (12, '12'), (16, '16'), (18, '18')], verbose_name='Возрастное ограничение'),
        ),
    ]
